# Project: 4.9【LGR-276-Div.3】洛谷蓝桥杯省赛模拟赛 2026 补题
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = "../4.9【LGR-276-Div.3】洛谷蓝桥杯省赛模拟赛\ 2026\ 不题/main.o"
LINKOBJ  = "../4.9【LGR-276-Div.3】洛谷蓝桥杯省赛模拟赛 2026 不题/main.o"
LIBS     = -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "4.9【LGR-276-Div.3】洛谷蓝桥杯省赛模拟赛 2026 补题.exe"
CXXFLAGS = $(CXXINCS) -Og -std=gnu++11 -g3 -std=c++11
CFLAGS   = $(INCS) -Og -std=gnu++11 -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"../4.9【LGR-276-Div.3】洛谷蓝桥杯省赛模拟赛\ 2026\ 不题/main.o": ../4.9【LGR-276-Div.3】洛谷蓝桥杯省赛模拟赛\ 2026\ 不题/main.cpp
	$(CPP) -c "../4.9【LGR-276-Div.3】洛谷蓝桥杯省赛模拟赛 2026 不题/main.cpp" -o "../4.9【LGR-276-Div.3】洛谷蓝桥杯省赛模拟赛 2026 不题/main.o" $(CXXFLAGS)
